fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "openssl": "git://github.com/camptocamp/puppet-openssl.git"
    "java_ks" : "git://github.com/puppetlabs/puppetlabs-java_ks.git"
  symlinks:
    "java": "#{source_dir}"
